language: node_js

env:
  - CXX=g++-4.8

node_js:
  - '12.7.0'
  - '10.16.0'
  - '8.16.0'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email: false

sudo: false

before_install:
  - $CXX --version
